# Example configuration file
# This file can be split up how you like as long as the files end in *.toml

# global is reserved for permission sets across both explicit clients and anonymous clients
[global]
read = []
write = []
# main encryption key. Not recommended to be put here, but why not offer the convenience? 
key = ""
# custom salt for main key
salt = ""

# Specific clients are defined in this file by name
[server1]
# Token is used by passing as an HTTP header: X-API-Key
token = "SecretKeyHere"
# Read grants read permissions to specific paths of secret
read = ["aws/*", "slack/api_token"]
# Write grants write permissions to paths of secret
write = ["server2/*"]

# this token can only read or write its own secrets
[server2]
token = "SecondSecretKey"
read = []
write = []